### ISSUE TITLE
Unable to start integration since update to 2025.1.1

### ISSUE THREAD

**Issue by evakq8r** [sockless-coding/panasonic_cc#363]
### Checklist

- [X] I have verified that the account and device works in the Comfort Cloud App.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

core-2024.12.5

### Describe the issue

Upgraded to 2025.1.1, integration fails to start for the error log below. Rolling back to 2024.11.0 resolves the error.

If the reason is because I'm not using 2025.1.1 for the HAOS core, that's fine - I'll roll back/reinstall from 2024.12.5 as I'm not upgrading the core at the moment.

### Error/Debug Logs

```text
Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 11 January 2025 at 23:29:59 (2 occurrences)
Last logged: 00:42:43

Error setting up entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 138, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, COMPONENT_TYPES)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2278, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  [Previous line repeated 4 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1172, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1097, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1271, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1303, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/panasonic_cc/water_heater.py", line 8, in <module>
    from homeassistant.components.water_heater import (
    ...<4 lines>...
    )
ImportError: cannot import name 'WaterHeaterEntityDescription' from 'homeassistant.components.water_heater' (/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py)
```

**Comment by sockless-coding** [comment]
@evakq8r yes, it seems that `WaterHeaterEntityDescription` was introduced in 2025.1 prior to that version it was called `WaterHeaterEntityEntityDescription`...
Version 2025.1.0 should work, 2025.1.1 is mainly Aquarea stuff

**Comment by evakq8r** [comment]
> @evakq8r yes, it seems that `WaterHeaterEntityDescription` was introduced in 2025.1 prior to that version it was called `WaterHeaterEntityEntityDescription`...
> Version 2025.1.0 should work, 2025.1.1 is mainly Aquarea stuff

No problem, thanks for the response.

I'll close this report off

**Comment by sockless-coding** [comment]
@evakq8r give 2025.1.2 a try I added a conditional import so it should work with HA 2024.12 now.

**Comment by evakq8r** [comment]
> @evakq8r give 2025.1.2 a try I added a conditional import so it should work with HA 2024.12 now.

Perfect, that works a treat. Thanks very much @sockless-coding!
