### ISSUE TITLE
Panasonic Comfort Cloud stopped working

### ISSUE THREAD

**Issue by bym007** [sockless-coding/panasonic_cc#393]
### Checklist

- [x] I have verified that the account and device works in the Comfort Cloud App.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

2025.4.4

### Describe the issue

The Panasonic integration stopped working.

### Error/Debug Logs

```text
Logger: aio_panasonic_comfort_cloud.helpers
Source: custom_components/panasonic_cc/__init__.py:80
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 14:21:10 (8 occurrences)
Last logged: 14:25:47

Error in get_groups Expected status code '200' but received '503' Response body: {"message":"05/08/2025 01:00 ～ 05/08/2025 07:00 (UTC ± 00)","code":5300}
Error in get_acc_client_id Expected status code '200' but received '503' Response body: {"message":"05/08/2025 01:00 ～ 05/08/2025 07:00 (UTC ± 00)","code":5300}
```

**Comment by evakq8r** [comment]
Came here to report the same thing, but looks to be 6 hours of system maintenance (from the app):

![Image](https://github.com/user-attachments/assets/b615496f-992b-4488-aac8-7ec90c0f2e77)

**Comment by bym007** [comment]
Thanks for updating. Somehow I didnt receive any notifications about the maintenance.

More importantly, it seems pretty off, taking their app offline during weekdays.

**Comment by evakq8r** [comment]
I didn't get any maintenance notifications either, but tried logging into the app and got hit by that.

1am to 7am isn't your typical business hours, but that's in UTC. Depending where you are in the world, it will be business hours "somewhere", so that is unavoidable.

**Comment by danis197** [comment]
Aquarea Smart Cloud intergration is also down

**Comment by hemaris-8b** [comment]
Panasonic service break is over and at least for me the integration seems to work normally again. There was also a forced update of the cell phone app, so apparently something has changed. Fortunately that did not seem to break the integration.

**Comment by ColdTruth0108** [comment]
HI, I noticed now that my heat pump does not work via HA. I also noticed that my android app has been updated and web access via browser has been disabled by Panasonic. Heat pump works via Panasonic app but I have no entieties available in the integration. Maybe there is a need to change something in the integration's source code?

**Comment by hemaris-8b** [comment]
> HI, I noticed now that my heat pump does not work via HA. I also noticed that my android app has been updated and web access via browser has been disabled by Panasonic. Heat pump works via Panasonic app but I have no entieties available in the integration. Maybe there is a need to change something in the integration's source code?

Have you tried to restart HA. That worked for me.

**Comment by ColdTruth0108** [comment]
> > HI, I noticed now that my heat pump does not work via HA. I also noticed that my android app has been updated and web access via browser has been disabled by Panasonic. Heat pump works via Panasonic app but I have no entieties available in the integration. Maybe there is a need to change something in the integration's source code?
> 
> Have you tried to restart HA. That worked for me.

Yes I did it, also i tried to reconfigure integration.

**Comment by jbayom** [comment]
I think Panasonic has disabled login via web, and so HA integration doesn't work now.....

**Comment by hemaris-8b** [comment]
> I think Panasonic has disabled login via web, and so HA integration doesn't work now.....

As I mentioned earlier, I do not see any problems with the integration. Also, no errors in the log.

![Image](https://github.com/user-attachments/assets/c84fb8e5-510d-4187-9341-2760ef8960d0)

![Image](https://github.com/user-attachments/assets/4eee64a7-1100-42d8-94c3-323b55583507)

**Comment by hemaris-8b** [comment]
> I can see.. .but, is it really updated? I can see my controls on Apple Home and HOmebrigde, but they're not updated....

Yes, it updates fine. I just used the phone app to change the temperature and saw the same change in HA

![Image](https://github.com/user-attachments/assets/ee3fc2a9-f9a7-4239-a427-0564907dc133)

**Comment by jbayom** [comment]
ok, and what kind of product (hw) do you have? I have a heat pump and heat water tank, with cz-taw1b/dz-taw1c wifi device.... This product has been migrated to comfort cloud yesterday. Maybe, this affects a certain products.... or depends about the device. Actually, I can't login via web/API nor shows devices

<img width="993" alt="Image" src="https://github.com/user-attachments/assets/2e1c119d-1202-4404-94d0-34d33fad4db3" />
<img width="1157" alt="Image" src="https://github.com/user-attachments/assets/f0a7fd49-87c1-445b-888d-651ff0242ab4" />

**Comment by hemaris-8b** [comment]
I have HZ25WKE air-to-air heat pump. Not sure which wifi module it has.

**Comment by SHCimRautenweg** [comment]
have you been using the Aquarea Smart Cloud integration and there all worked ok, and as the heatpump is switches off since some days i have not recognized that it is not working anymore. just a not that you should use the Panasonic Comfort Cloud, i installed it this morning and it did not work, looks like it worked in the past with HA.

**Comment by jbayom** [comment]
I have been using several integrations, for HA and for Homebridge. Since yesterday, doesn't work none of them.

**Comment by SHCimRautenweg** [comment]
i hope someone finds a solution, i am not as good as many others here and happy when i get an integation or add-on run but i am not a programmer. l assume more people have the issue and it will be taken care.

**Comment by jbayom** [comment]
It depends on Panasonic, I'm afraid...

**Comment by Th3M1k3y** [comment]
I had to log into the app and accept tos, after that both came back to life again.

**Comment by SHCimRautenweg** [comment]
may i ask what tos is.

**Comment by ColdTruth0108** [comment]
I think terms of service, but i didn't have such popup. Even after app reinstall.

**Comment by wado88** [comment]
i get this error in log
Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.panasonic_cc
Kilde: custom_components/panasonic_cc/__init__.py:110
integration: Panasonic Comfort Cloud (dokumentation, problemer)
Første forekomst: 20.11.42 (8 forekomster)
Senest logget: 20.41.25

Failed to setup Aquarea: 'NoneType' object has no attribute 'value'
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/__init__.py", line 110, in async_setup_entry
    await aquarea_api_client.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
i have accepted the new terms of service.

**Comment by bounty123** [comment]
I can confirm that the integration stipped working for me as well. I have a Panasonic Heat Pump. The application works.

**Comment by ColdTruth0108** [comment]
> i get this error in log
> Denne fejl stammer fra en brugerdefineret integration.
> 
> Logger: custom_components.panasonic_cc
> Kilde: custom_components/panasonic_cc/__init__.py:110
> integration: Panasonic Comfort Cloud (dokumentation, problemer)
> Første forekomst: 20.11.42 (8 forekomster)
> Senest logget: 20.41.25
> 
> Failed to setup Aquarea: 'NoneType' object has no attribute 'value'
> Traceback (most recent call last):
>   File "/config/custom_components/panasonic_cc/__init__.py", line 110, in async_setup_entry
>     await aquarea_api_client.login()
>   File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
>     await self.__login_production()
>   File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
>     auth_state = response.cookies.get("com.auth0.state").value
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'value'
> i have accepted the new terms of service.

I found the same error in logs.

**Comment by Martijnoh** [comment]
I also get the same error. Heatpump can still be controlled by the mobile app. When i look at recent logins in my panasonic account my home assistant instance doest show.

**Comment by crisking** [comment]
I am getting the same error. No device found.
I also use the “original” Aquarea integration (its library is included and used in this Confort Cloud integration since 2025.1.1) and error are similar.

It seems that library “aioaquarea” cannot connect 
correctly anymore after  Aquarea Service cloud portal closure and new Panasonic official app update.

Maybe Panasonic is still migrating something and Aquarea smart cloud services are not working fine yet or not available expect for their official app, at the moment.

Panasonic informed about a merge of web components some weeks ago by an official email to Aquarea Service Cloud users, where they informed of service cloud portal closure on 8/05/2025

**Comment by bartolomeo902** [comment]
It seems to me that the merge that Panasonic just did, broke the API access that the integration was using to gather data

**Comment by crisking** [comment]
> It seems to me that the merge that Panasonic just did, broke the API access that the integration was using to gather data

For sure

**Comment by phict** [comment]
change the app version in the headers to: `"X-APP-VERSION: 2.1.0"` and it should start working again.

**Comment by jbayom** [comment]
> change the app version in the headers to: `"X-APP-VERSION: 2.1.0"` and it should start working again.

where?

**Comment by phict** [comment]
> > change the app version in the headers to: `"X-APP-VERSION: 2.1.0"` and it should start working again.
> 
> where?

in the request to get the token. i dont use this lib but a similar one which also stopped working and when looking for a solution i found this thread, so when i got it working i shared the change that fixed it.

should be changed here https://github.com/sockless-coding/aio-panasonic-comfort-cloud/blob/master/aio_panasonic_comfort_cloud/constants.py

**Comment by martijnz43** [comment]
> > > change the app version in the headers to: `"X-APP-VERSION: 2.1.0"` and it should start working again.
> > 
> > 
> > where?
> 
> in the request to get the token. i dont use this lib but a similar one which also stopped working and when looking for a solution i found this thread, so when i got it working i shared the change that fixed it.
> 
> should be changed here https://github.com/sockless-coding/aio-panasonic-comfort-cloud/blob/master/aio_panasonic_comfort_cloud/constants.py

Is this for the developer of the integration or is there any way a user can change this in homeassistant to get things up and running in the meantime? For the integrations I don't see the source files in Homeassistant Studio code server but maybe I'm looking at the wrong place? 

I'm in contact with panasonic support about a bug in the device software (seems to be fixed now) but I've also send them the link to this discussion and suggested that they take a more active approach in informing the community about changes that affect integrations with smart home solutions like homeassistant. Would be nice if they take the time to post the changes when they perform an update and make it easier to adjust the integration to the new situation.

**Comment by bartolomeo902** [comment]
I also tried to personalize the headers but it seems that the integration uses the external package "aio-panasonic-comfort-cloud" to interact with the Panasonic API. Thus, I'm not able to customize the headers unless I was to download the package itself, modify it and make panasonic_cc point to that package. All of this is becoming a bit too advanced for me. Let's hope the developer will quickly address this issue and release an hotfix for it

**Comment by sockless-coding** [comment]
I had a look around, it seems like the old Web Interface for Aquarea is gone.
I need some debug logs from someone with an Aquarea device.

![Image](https://github.com/user-attachments/assets/ff6094f5-e366-4f91-ace2-b5004da79364)

> [!CAUTION]
> Make sure to remove any tokens or other sensitive data before posting logs

**Comment by wado88** [comment]
[home-assistant_panasonic_cc_2025-05-12T17-58-33.364Z.log](https://github.com/user-attachments/files/20169236/home-assistant_panasonic_cc_2025-05-12T17-58-33.364Z.log)

here hope it worked.

**Comment by sockless-coding** [comment]
@wado88 thanks for the log, unforunatly it didn't provide much info. I thought I had more logging but I must have removed that when I added the Aquarea lib...

**Comment by martijnz43** [comment]
And another one but don't think it gives more info:
2025-05-12 20:02:54.677 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxx@xxxx.nl for aquarea
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aquarea/__init__.py", line 47, in async_setup_entry
    await client.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by maccan-tech** [comment]
Here is the output from the python script.
I hope i have not REDACTED to little or too much

```
DEBUG    | 2025-05-12 21:13:20 | asyncio | Using selector: EpollSelector
DEBUG    | 2025-05-12 21:13:20 | aio_panasonic_comfort_cloud.panasonicsession | Starting Session
DEBUG    | 2025-05-12 21:13:20 | aio_panasonic_comfort_cloud.panasonicsettings | Loaded settings from '/home/maccan/.panasonic-settings'
DEBUG    | 2025-05-12 21:13:20 | aio_panasonic_comfort_cloud.panasonicsession | Access token is valid
DEBUG    | 2025-05-12 21:13:20 | aio_panasonic_comfort_cloud.panasonicrequestheader | Request Timestamp: 2025-05-12 21:13:20 key: [REDACTED]
DEBUG    | 2025-05-12 21:13:21 | aio_panasonic_comfort_cloud.panasonicsession | GET url: https://accsmart.panasonic.com/device/group, response: {"a2wStatus":{"statusCode":200},"uiFlg":false,"groupCount":1,"groupList":[{"groupId":[REDACTED],"groupName":"My House","pairingList":[],"deviceList":[{"deviceGuid":"[REDACTED]","deviceType":"2","deviceName":"Garage","connectionStatus":0,"operationMode":1,"zoneStatus":[{"zoneId":1,"operationStatus":0,"temperature":-5},{"zoneId":2}],"tankStatus":{}}]}]}
Found 0 device(s) and 1 unknown devices:
 - Garage ()
DEBUG    | 2025-05-12 21:13:21 | aio_panasonic_comfort_cloud.panasonicrequestheader | Request Timestamp: 2025-05-12 21:13:21 key: [REDACTED]
ERROR    | 2025-05-12 21:13:21 | aio_panasonic_comfort_cloud.helpers | Error in get_status
Expected status code '200' but received '403'
Response body: {"code":4300,"message":"Have no authority to the request"}
WARNING  | 2025-05-12 21:13:21 | aio_panasonic_comfort_cloud.apiclient | Failed to get live status for device B693281694 switching to cached data.
DEBUG    | 2025-05-12 21:13:21 | aio_panasonic_comfort_cloud.panasonicrequestheader | Request Timestamp: 2025-05-12 21:13:21 key: [REDACTED]
ERROR    | 2025-05-12 21:13:22 | aio_panasonic_comfort_cloud.helpers | Error in get_status
Expected status code '200' but received '403'
Response body: {"code":4300,"message":"Have no authority to the request"}
Failed to fetch device status
```

**Comment by sockless-coding** [comment]
That contains enough information to determine that they haven't just moved the Aquarea into the normal Panasonic Api calls.
So, reverse-engineering of the App is needed to see what calls are made when controlling Aquarea devices.

**Comment by sockless-coding** [comment]
@maccan-tech I've updated the `aio-panasonic-comfort-cloud` lib to v2025.5.0 and changed the sample to call `await api.get_aquarea_device(device)` for the aquarea devices. Can you give it a try?

**Comment by wado88** [comment]
so how do we update the lib? can we do it from HACS?

**Comment by Link-1110** [comment]
> so how do we update the lib? can we do it from HACS?

Yes, when it's available, I'm also looking forward to it!!

**Comment by Link-1110** [comment]
How do I update to the latest version that seems to work?

**Comment by sockless-coding** [comment]
Unfortunately, since the a2winfo only returns `{"result":0}` we still don't have a way to fetch the Aquarea device info.

**Comment by wrcvr4** [comment]
I posted this comment into a different issue
https://github.com/cjaliaga/home-assistant-aquarea/issues/139#issuecomment-2885504625

Switched from SMS to Authenticator yesterday, running this python script, I can now authenticate and it shows 5 devices found
```
DEBUG    | 2025-05-17 08:37:51 | aio_panasonic_comfort_cloud.panasonicsession | GET url: https://accsmart.panasonic.com/device/group, response:
Found 5 device(s) and 0 unknown devices:
```

HACS integration will still not setup (might need to wait for the that update?)

**Comment by sockless-coding** [comment]
@wrcvr4, your issue seems to be authentication-related, the Authentication works best if you create a separate account for Home Assistant and use the SMS authentication. The TOTP will not work, and if you use the same account in the App your HA might get logged out.

**Comment by wrcvr4** [comment]
> [@wrcvr4](https://github.com/wrcvr4), your issue seems to be authentication-related, the Authentication works best if you create a separate account for Home Assistant and use the SMS authentication. The TOTP will not work, and if you use the same account in the App your HA might get logged out.

Thanks, I will try this

**Comment by wrcvr4** [comment]
@sockless-coding done this and still get the same error in Hass
Do you want me to add a new Issue for this ?
`
aio_panasonic_comfort_cloud.exceptions.ResponseError: (get_token: Expected status code 200, received: 400: {"error":"invalid_request","error_description":"Missing required parameter: code"}`

**Comment by wrcvr4** [comment]
I seem to have fixed my issue, by doing 1 of 2 things (Only saw 5 of 6 units)
1) Updated aio-panasonic-comfort-cloud==2025.5.0 in the manifest,json
2) trying to auth with an incorrect password and then the correct one

**Comment by Link-1110** [comment]
Hello, can someone take 5 minutes to tell me how to upgrade to version 2025.5 to help you? I have a Panasonic Aquarea pump but I can't find how to upgrade my version. Please explain the steps in detail.

**Comment by wrcvr4** [comment]
@Link-1110 You need to access the share on Hass
Goto this file `config\custom_components\panasonic_cc\manifest.json`
Change the aio-panasonic-comfort-cloud like below (remember to write down the current value, so you can revert if needed)
`"requirements": ["aiohttp","aio-panasonic-comfort-cloud==2025.5.0","aioaquarea==0.7.2"],`
Save the file (Might need to then reboot)

**Comment by jbayom** [comment]
> [@Link-1110](https://github.com/Link-1110) You need to access the share on Hass Goto this file `config\custom_components\panasonic_cc\manifest.json` Change the aio-panasonic-comfort-cloud like below (remember to write down the current value, so you can revert if needed), not sure if Aquarea has a new version, below worked for my splits/multi-split `"requirements": ["aiohttp","aio-panasonic-comfort-cloud==2025.5.0","aioaquarea==0.7.2"],` Save the file (Might need to then reboot)

hello

It doesn't work. No devices found. Do I have to change anything else?

**Comment by ColdTruth0108** [comment]
After update integration to 2025.5.0 i tried to set up it again from scratch and when I provides credentials and I click submit i gets unknown error:

![Image](https://github.com/user-attachments/assets/64501c18-b696-4e8f-b34e-76fbe6c11301)

 and in HA logs I see:

![Image](https://github.com/user-attachments/assets/1533cd67-7298-4e84-9a01-d2a949f1aa6e)

**Comment by pkaras62a** [comment]
No luck, it is still missing the auth0 cookie:
```
This error originated from a custom integration.

Logger: custom_components.panasonic_cc
Source: custom_components/panasonic_cc/__init__.py:126
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 10:50:16 (1 occurrence)
Last logged: 10:50:16

Failed to setup Aquarea: 'NoneType' object has no attribute 'value'
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/__init__.py", line 126, in async_setup_entry
    await aquarea_api_client.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by Link-1110** [comment]
Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.panasonic_cc
Source: custom_components/panasonic_cc/__init__.py:126
intégration: Panasonic Comfort Cloud (documentation, problèmes)
S'est produit pour la première fois: 15:10:51 (1 occurrence)
Dernier enregistrement: 15:10:51

Failed to setup Aquarea: 'NoneType' object has no attribute 'value'
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/__init__.py", line 126, in async_setup_entry
    await aquarea_api_client.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by sockless-coding** [comment]
The Aquarea part is still broken, waiting for that lib to be updated.

**Comment by larayorch** [comment]
So just to get this straight, we should NOT update to version 2025.5.0 of the integration until this aquarea library issue is fixed?

**Comment by ZegarekPL** [comment]
This is not an issue with the panasonic_cc integration itself, but rather with the [aioaquarea](https://github.com/cjaliaga/aioaquarea) library that panasonic_cc depends on. Therefore, this issue doesn't apply to this repository.

Someone has already opened an issue in the correct place:
https://github.com/cjaliaga/aioaquarea/issues/51

**Comment by larayorch** [comment]
My question comes because I'm currently on HA 2025.5.3 but my Panasonic integration is on version 2025.1.2, I have not upgraded to version 2025.5.0, and my Panasonic integration is working perfectly fine. I understand the issue is now with the aquarea library, but I'm guessing this issue starts giving trouble on version 2025.5.0 of the Panasonic integration, as my current 2025.1.2 is working normally.

Have any users on 2025.5.0 with the issue tried reverting to version 2025.1.2 and see if it works?

**Comment by ZegarekPL** [comment]
> My question comes because I'm currently on HA 2025.5.3 but my Panasonic integration is on version 2025.1.2, I have not upgraded to version 2025.5.0, and my Panasonic integration is working perfectly fine. I understand the issue is now with the aquarea library, but I'm guessing this issue starts giving trouble on version 2025.5.0 of the Panasonic integration, as my current 2025.1.2 is working normally.
> 
> Have any users on 2025.5.0 with the issue tried reverting to version 2025.1.2 and see if it works?

I downgraded from version 2025.5.0 to 2025.1.2 about 5 minutes ago, but the issue is still the same

**Comment by Jaroslaw-ja** [comment]
Niestety mam ten sam problem
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/__init__.py", line 126, in async_setup_entry
    await aquarea_api_client.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by Jaroslaw-ja** [comment]
Login Issue: AttributeError: 'NoneType' object has no attribute 'value'

Hi,
After starting the panasonic_cc integration in Home Assistant, I'm encountering the following error:

Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/__init__.py", line 126, in async_setup_entry
    await aquarea_api_client.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

It looks like response.cookies.get("com.auth0.state") is returning None, which leads to this error when trying to access .value.

**Comment by SHCimRautenweg** [comment]
i have contacted Panasonic and asked if they plan to change the API so that an access is again possible. the only answer i got it that A/C are now controllable through Google Home and Alexa as the comfort cloud is no avalible for Google home. i wonder if it is possible to get access in HA though the Google Cast Integration.

**Comment by arjanvandijk1990-cpu** [comment]
Still not an update about this one?

**Comment by hyzteric** [comment]
> i have contacted Panasonic and asked if they plan to change the API so that an access is again possible. the only answer i got it that A/C are now controllable through Google Home and Alexa as the comfort cloud is no avalible for Google home. i wonder if it is possible to get access in HA though the Google Cast Integration.

There is a Panasonic Comfort Cloud available in Google Home but when I add it to my house (you have to authenticate), it says no device is compatible and will stop and not add the Panasonic service.

**Comment by asbor** [comment]
Following..... got same issue...

**Comment by matssk** [comment]
I just managed to configure a Sensibo Sky that seems to works ok as an alternative remote control that gets around Comfort Cloud not working.

**Comment by larayorch** [comment]
I am just stopping by to say my integration NEVER stopped working and is STILL working. I never upgraded the integration from version 2025.1.2, I am still on that version, and I'm on the latest version of HA (2025.9.4) and HA OS (16.2), and everything is working normally. Is there any data I could provide or share that could help sort out why it is still working for me and not working for so many?

**Comment by Hesseland** [comment]
I succesfully confirgured the hub, but no entities where found.  I've tried is a couple of times en restated the HA. How can i solve this problem

<img width="1046" height="265" alt="Image" src="https://github.com/user-attachments/assets/44686278-d8f9-4a36-b708-1d95240b6da9" />

**Comment by hyzteric** [comment]
Same here... same here...

**Comment by asbor** [comment]
an update from my end, i decided to take another route, https://github.com/IgorYbema/HeishaMon i ordered a circuit board connected it to the heat pump and its working fine. I'm very happy with the result!
