### ISSUE TITLE
Failed to setup Aquarea: 'NoneType' object has no attribute 'value' on login (com.auth0.state)

### ISSUE THREAD

**Issue by ezequielgn** [sockless-coding/panasonic_cc#414]
### Checklist

- [x] I have verified that the account and device works in the Comfort Cloud App.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

core-2025.10.3

### Describe the issue

Hello, I am having issues setting up my Aquarea device. The integration logs in (I don't get an 'invalid login' error), but it fails to fetch the device (Got 0 devices). The debug log shows the following repeated error during the login process:

WARNING (MainThread) [custom_components.panasonic_cc] Failed to setup Aquarea: 'NoneType' object has no attribute 'value'
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/__init__.py", line 126, in async_setup_entry
    await aquarea_api_client.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

It seems the login process isn't correctly receiving the com.auth0.state cookie. This might be related to a complex account ownership issue I had in the past.

### Error/Debug Logs

```text

```

**Comment by kaliseo** [comment]
Same here !

**Comment by ezequielgn** [comment]
UPDATE: I have just re-tested the integration using the original "Owner" account for my Aquarea.

Unfortunately, the integration still fails with the exact same error: AttributeError: 'NoneType' object has no attribute 'value' on line auth_state = response.cookies.get("com.auth0.state").value.

This confirms the bug is not related to account permissions, but a deeper issue in the login flow.

**Comment by ezequielgn** [comment]
This is getting complicated. After updating Home Assistant Core to 2025.10.4, the integration is now failing in two different ways:

1. When I try to log in with my "Owner" account, it fails with a new error: {"error":"invalid_request","error_description":"Missing required parameter: code"}

2. If I log in with my "Secondary" account, the login is successful, but it still fails to set up the device with the original bug: AttributeError: 'NoneType' object has no attribute 'value' on line auth_state = response.cookies.get("com.auth0.state").value

It seems the HA Core update has introduced a new login issue, on top of the original device setup bug.

**Comment by tbandras** [comment]
I must say, I am slightly confused: I have the same issue that you described in the initial post, but there still seem to be some people who have their Aquarea heat pumps mapped and working with Home Assistant:

- When I log in with my owner account I can only see the an AC unit added, the heat pump is not present
- I have created a secondary account for the heat pump: if I remove the owner account and map the integration with the secondary account, I still get the AC and not the HP
- I set up 2FA for both accounts: the only time I have been prompted for an SMS code was during the setup itself
- I found [this integration](https://github.com/cjaliaga/home-assistant-aquarea), which people claim to work, but I am running into different issues with it (it does not recognize the secondary account)

**Comment by tbandras** [comment]
> I must say, I am slightly confused: I have the same issue that you described in the initial post, but there still seem to be some people who have their Aquarea heat pumps mapped and working with Home Assistant:
> 
> * When I log in with my owner account I can only see the an AC unit added, the heat pump is not present
> * I have created a secondary account for the heat pump: if I remove the owner account and map the integration with the secondary account, I still get the AC and not the HP
> * I set up 2FA for both accounts: the only time I have been prompted for an SMS code was during the setup itself
> * I found [this integration](https://github.com/cjaliaga/home-assistant-aquarea), which people claim to work, but I am running into different issues with it (it does not recognize the secondary account)

Short update: [this integration](https://github.com/wpatrik14/aioaquarea) seems to work - after logging in with a secondary account that I created specifically for integrating with HA (and added the HP to it), all details come up (actually more than what I see in CC)

**Comment by aliaskongen-hash** [comment]
Same issue as this, does anyone have a solution to this problem? It will not add any entities when logging in. 

Logger: custom_components.panasonic_cc
Kilde: custom_components/panasonic_cc/__init__.py:126
integration: Panasonic Comfort Cloud ([dokumentation](https://github.com/sockless-coding/panasonic_cc/), [problemer](https://github.com/sockless-coding/panasonic_cc/issues))
Første forekomst: 22.13.14 (2 forekomster)
Senest logget: 22.21.41

Failed to setup Aquarea: 'NoneType' object has no attribute 'value'
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/__init__.py", line 126, in async_setup_entry
    await aquarea_api_client.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by joene-nl** [comment]
> > I must say, I am slightly confused: I have the same issue that you described in the initial post, but there still seem to be some people who have their Aquarea heat pumps mapped and working with Home Assistant:
> > 
> > * When I log in with my owner account I can only see the an AC unit added, the heat pump is not present
> > * I have created a secondary account for the heat pump: if I remove the owner account and map the integration with the secondary account, I still get the AC and not the HP
> > * I set up 2FA for both accounts: the only time I have been prompted for an SMS code was during the setup itself
> > * I found [this integration](https://github.com/cjaliaga/home-assistant-aquarea), which people claim to work, but I am running into different issues with it (it does not recognize the secondary account)
> 
> Short update: [this integration](https://github.com/wpatrik14/aioaquarea) seems to work - after logging in with a secondary account that I created specifically for integrating with HA (and added the HP to it), all details come up (actually more than what I see in CC)

The second account is another panasonic ID? Or am I missing something?

**Comment by Thomas-Dahl** [comment]
I also have the nonetype error, anyone managed to solve this?
Tried with both a main and a secondary account.

This error originated from a custom integration.

Logger: custom_components.panasonic_cc
Source: custom_components/panasonic_cc/__init__.py:126
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 8:20:06 AM (4 occurrences)
Last logged: 9:08:59 AM

Failed to setup Aquarea: 'NoneType' object has no attribute 'value'
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/__init__.py", line 126, in async_setup_entry
    await aquarea_api_client.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by joene-nl** [comment]
> I also have the nonetype error, anyone managed to solve this? Tried with both a main and a secondary account.
> 
> This error originated from a custom integration.
> 
> Logger: custom_components.panasonic_cc Source: custom_components/panasonic_cc/**init**.py:126 integration: Panasonic Comfort Cloud (documentation, issues) First occurred: 8:20:06 AM (4 occurrences) Last logged: 9:08:59 AM
> 
> Failed to setup Aquarea: 'NoneType' object has no attribute 'value' Traceback (most recent call last): File "/config/custom_components/panasonic_cc/**init**.py", line 126, in async_setup_entry await aquarea_api_client.login() File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login await self.__login_production() File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production auth_state = response.cookies.get("com.auth0.state").value ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'value'

Nope got the same error, have not found a solution yet…

**Comment by aliaskongen-hash** [comment]
Hi - I solved it by updating the script to use newer version of aioaquarea
[https://github.com/sockless-coding/panasonic_cc/pull/412](url)

**Comment by joene-nl** [comment]
> Hi - I solved it by updating the script to use newer version of aioaquarea [https://github.com/sockless-coding/panasonic_cc/pull/412](url)

How/what did you update to the newer version of aioaquarea? Is that just a matter of updating the manifest.json to make sure it uses aioaquarea 1.0.2 instead of 0.7.2 in the panasonic_cc or something?

**Comment by HannesVDV** [comment]
> > Hi - I solved it by updating the script to use newer version of aioaquarea [https://github.com/sockless-coding/panasonic_cc/pull/412](url)
> 
> How/what did you update to the newer version of aioaquarea? Is that just a matter of updating the manifest.json to make sure it uses aioaquarea 1.0.2 instead of 0.7.2 in the panasonic_cc or something?

I made a fork of the repo and merged the pull request. That fixed the error for me.

**Comment by joene-nl** [comment]
> > > Hi - I solved it by updating the script to use newer version of aioaquarea [https://github.com/sockless-coding/panasonic_cc/pull/412](url)
> > 
> > 
> > How/what did you update to the newer version of aioaquarea? Is that just a matter of updating the manifest.json to make sure it uses aioaquarea 1.0.2 instead of 0.7.2 in the panasonic_cc or something?
> 
> I made a fork of the repo and merged the pull request. That fixed the error for me.

Thanks for the reply, I already downloaded all the files from the pull request and managed to get panasonic devices to work in HA. Now I also created a fork and merged the changes.

**Comment by ezequielgn** [comment]
**Definitive solution found for Aquarea Smart Cloud users**
Hi everyone,
I wanted to provide an update on my experience. After struggling with the main panasonic_cc integration for my Panasonic Aquarea heat pump, I found a working solution using a specific fork.

For those using Aquarea Smart Cloud (not Comfort Cloud), the integration by @wpatrik14 works perfectly: [https://github.com/wpatrik14/home-assistant-aquarea](https://github.com/wpatrik14/home-assistant-aquarea)

Status update: * Version: Working flawlessly on Home Assistant 2026.1.3 and 2026.2.0.
- Entities: It correctly pulls data for Outdoor Temperature, DHW Tank, and full Climate Control (Heating/Cooling).
- Stability: Very stable. I even implemented a staggered startup automation (2-minute delay after reboot) to ensure the network is ready before the integration attempts to refresh the token, which solved previous authentication issues.

I highly recommend switching to this repository if you are facing "NoneType" or authentication errors with the standard integration. Thanks to the community and especially to @wpatrik14 for this great work!

**Comment by sockless-coding** [comment]
This issue has been resolved in newer releases, so I’m closing it.
If it still occurs on the latest version, please open a new issue.
