### ISSUE TITLE
"Created configuration for ."

### ISSUE THREAD

**Issue by tn8or** [sockless-coding/panasonic_cc#415]
### Checklist

- [x] I have verified that the account and device works in the Comfort Cloud App.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

core-2025.10.4

### Describe the issue

I've both a primary and a secondary Panasonic CC account, both configured with SMS 2FA.
In both cases, when I try to add the integration to HA, it seems to accept the username/password (without prompting for 2FA) and then pauses for a second, and reports "Created configuration for .". Then, an empty integration appears (no entities, devices etc)

### Error/Debug Logs

```text
2025-11-03 18:19:07.000 WARNING (MainThread) [custom_components.panasonic_cc] Failed to setup Aquarea: 'NoneType' object has no attribute 'value'
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/__init__.py", line 126, in async_setup_entry
    await aquarea_api_client.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
2025-11-03 18:19:22.676 WARNING (MainThread) [homeassistant.components.cloud.google_config] Error reporting state - 14: Stream refused by server
2025-11-03 18:21:28.881 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'panasonic_cc' sets option flow config_entry explicitly, which is deprecated at custom_components/panasonic_cc/config_flow.py, line 191: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues
2025-11-03 18:22:22.892 INFO (MainThread) [custom_components.panasonic_cc] Updating configuration
2025-11-03 18:22:22.892 INFO (MainThread) [custom_components.panasonic_cc] Got 0 devices
2025-11-03 18:22:22.989 WARNING (MainThread) [custom_components.panasonic_cc] Failed to setup Aquarea: 'NoneType' object has no attribute 'value'
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/__init__.py", line 126, in async_setup_entry
    await aquarea_api_client.login()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.13/site-packages/aioaquarea/core.py", line 298, in __login_production
    auth_state = response.cookies.get("com.auth0.state").value
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'value'
```

**Comment by b3ndev** [comment]
I have the same issue on my side with same logs.
I have the same weird behaviour : after setting up 2FA with SMS, when I connect with comfort cloud or via the HA Integration I do not receive any SMS to authenticate.

**Comment by cadilu** [comment]
I´m afraid that I´m suffering from the same issue, even if my credentials are wrong nothing happens

**Comment by sebeeek** [comment]
This looks like a duplicate of #414

**Comment by Klisterkongen** [comment]
same issue here. T-cap Aquarea not comming online.
